spring.application.name=demowithswiggy

# MySQL database
spring.datasource.url=jdbc:mysql://localhost:3306/demowithswiggy?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Subhiksha@Meow

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
